### PR TITLE
Rewrite README a bit

### PR DESCRIPTION
**Pull request by m-rtijn**
Consistent naming and fixed some spelling issues.

### CODE REVIEW

**Comment by the-eater** [comment]
Do you know that all dependencies are GPLv3 compatible?

**Comment by m-rtijn** [comment]
So I have checked all dependencies, and all was fine until I checked `ring`. It turns out that `ring` is derived from BoringSSL, which in turn is a fork of OpenSSL. This means that the `ring` dependancy has code licensed under the OpenSSL license. This is a bit of a pain, because OpenSSL license is sadly incompatible with the GPL (any version). There apparently are ways to add an exception for OpenSSL to the GPL license, but I'm no legal expert so it might be easier to just choose the MIT License or the Apache 2 License.

**Comment by the-eater** [comment]
I guess MIT is the easiest choice?

**Comment by the-eater** [comment]
So after discussion, I will LICENSE it w/ MIT and we'll re-license if needed. will you edit the README accordingly @Tijndagamer? or you want me to do it?

**Comment by m-rtijn** [comment]
I've updated the `README.md` accordingly, with a note about planned re-licenseing. I also added a `LICENSE` file (maybe it should be called `COPYING`, but that's not a big deal).

**Comment by the-eater** [comment]
Thanks @Tijndagamer!!

**Comment by m-rtijn** [comment]
Happy to help :)

**Pull request merged**
